openapi: 3.0.3
info:
  title: Library API
  version: 1.2.2
  description: STD22016
servers:
  - url: https://library.com
tags:
  - name: Books
  - name: Authors
paths:
  /books:
    get:
      tags:
        - Books
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - in: query
          name: bookName
          description: Filter return books by given name
          required: false
          schema:
            type: string
        # TODO3: add parameter to filter books by intervals of dates of the releaseDate
        - in: query
          name: releaseDateStart
          description: Filter books by start date of release
          required: false
          schema:
            type: string
            format: date
        - in: query
          name: releaseDateEnd
          description: Filter books by end date of release
          required: false
          schema:
            type: string
            format: date
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'
      responses:
        200:
          $ref: '#/components/responses/BookList-200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'        
    put:
      tags:
        - Books
      summary: Create or update a list of books
      operationId: crupdateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Book'
      responses:
        200:
          $ref: '#/components/responses/BookList-200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /authors:
    get:
      tags:
        - Authors
      summary: Get all authors
      description: Get a list of all authors or filter by name.
      operationId: getAuthors
      parameters:
        - in: query
          name: authorName
          description: Filter authors by name
          required: false
          schema:
            type: string
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'
      responses:
        200:
          $ref: '#/components/responses/BookList-200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
    put:
      tags:
        - Authors
      summary: Create or update an author
      operationId: crupdateAuthor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        200:
          $ref: '#/components/responses/BookList-200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
    delete:
      tags:
        - Authors
      summary: Delete an author
      operationId: deleteAuthor
      parameters:
        - in: query
          name: authorId
          description: ID of the author to delete
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/BookList-200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /books/{bookId}/authors/{authorId}:
    put:
      summary: update author's book
      parameters:
        - in: path
          name: bookId
          required: true
          schema:
            type: integer
            format: int64
          description: ID book to update
        - in: path
          name: authorId
          required: true
          schema:
            type: integer
            format: int64
          description: New Id author
      responses:
        200:
          $ref: '#/components/responses/BookList-200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /books/authors:
    put:
      summary: Update authors for multiple books
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  bookId:
                    type: integer
                    format: int64
                    description: The ID of the book to update
                  authorId:
                    type: integer
                    format: int64
                    description: The ID of the new author
                required:
                  - bookId
                  - authorId
      responses:
        200:
          $ref: '#/components/responses/BookList-200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /books/import:
    post:
      tags:
        - Books
      summary: Import books from file
      operationId: importBooks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  $ref: '#/components/schemas/ImportData'
          application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
            schema:
              type: object
              properties:
                data:
                  $ref: '#/components/schemas/ImportData'
      responses:
        200:
          $ref: '#/components/responses/BookList-200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /authors/import:
    post:
      tags:
        - Authors
      summary: Import authors from file
      operationId: importAuthors
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  $ref: '#/components/schemas/ImportData'
          application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
            schema:
              type: object
              properties:
                data:
                  $ref: '#/components/schemas/ImportData'
      responses:
        200:
          $ref: '#/components/responses/BookList-200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        author:
          # TODO1: set it as a component with properties : id, name, sex (M or F)
          $ref: '#/components/schemas/Author'
        CrupdateBook:
          $ref: '#/components/schemas/CrupdateBook'
    Author:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        sex:
          type: string
          enum:
            - M
            - F
    CrupdateBook:
      type: object
      properties:
        ID:
          type: integer
        bookName:
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
        releaseDate:
          type: string
          format: date
    DefaultResponse:
      type: object
      properties:
        status:
          type: object
          properties:
            code:
              type: integer
              example: 200
            message:
              type: string
        body:
          type: object
    BadRequestBody:
      allOf:
        - $ref: '#/components/schemas/DefaultResponse'
      example:
        status:
          code: 400
          message: Bad Request
        body: { }
    BookListBody:
      allOf:
        - $ref: '#/components/schemas/DefaultResponse'
        - properties:
            body:
              type: array
              items:
                $ref: '#/components/schemas/Book'
    ImportAuthor:
      type: object
      properties:
        authorName:
          type: string
        sex:
          type: string
          enum:
            - M
            - F
      required:
        - authorName
        - sex

    ImportBook:
      type: object
      properties:
        bookName:
          type: string
        author:
          type: string
          description: ID of the author
        pageNumbers:
          type: integer
        topic:
          type: string
        releaseDate:
          type: string
          format: date
        idAuthor:
          type: string
          description: ID of the author
      required:
        - bookName
        - author
        - pageNumbers
        - topic
        - releaseDate
        - idAuthor
    ImportData:
      oneOf:
        - $ref: '#/components/schemas/ImportAuthor'
        - $ref: '#/components/schemas/ImportBook'
  responses:
    BookList-200:
      description: list of books
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BookListBody'
    400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestBody'
    403:
      description: Forbiden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestBody'
    500:
      description: Internal server
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestBody'
  parameters:
    Page:
      in: query
      name: page
      description: Page number
      required: false
      schema:
        type: integer
        default: 1

    PageSize:
      in: path
      name: page
      required: true
      schema:
        type: integer
        default: 30
