openapi: 3.0.3
info:
  title: Library API
  version: 1.2.2
  description: STD22016
servers:
  - url: https://library.com
tags:
  - name: Books
  - name: Authors
paths:
  /books:
    get:
      tags:
        - Books
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - in: query
          name: bookName
          description: Filter return books by given name
          required: false
          schema:
            type: string
        # TODO3: add parameter to filter books by intervals of dates of the releaseDate
        - in: query
          name: releaseDateStart
          description: Filter books by start date of release
          required: false
          schema:
            type: string
            format: date
        - in: query
          name: releaseDateEnd
          description: Filter books by end date of release
          required: false
          schema:
            type: string
            format: date
        - $ref: '#/components/parameters/queryPagination'
        - in: query
          name: pageSize
          description: Number of items per page
          required: false
          schema:
            type: integer
            default: 50
      responses:
        200:
          description: The list of filtered books
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200'
    put:
      tags:
        - Books
      summary: Create or update a list of books
      operationId: crupdateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Book'
      responses:
        200:
          description: The list of created or updated books
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200'
  /authors:
    get:
      tags:
        - Authors
      summary: Get all authors
      description: Get a list of all authors or filter by name.
      operationId: getAuthors
      parameters:
        - in: query
          name: authorName
          description: Filter authors by name
          required: false
          schema:
            type: string
        - $ref: '#/components/parameters/queryPagination'
        - in: query
          name: pageSize
          description: Number of items per page
          required: false
          schema:
            type: integer
            default: 50
      responses:
        200:
          description: The list of authors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200'
    put:
      tags:
        - Authors
      summary: Create or update an author
      operationId: crupdateAuthor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        200:
          description: The created or updated author
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200'
    delete:
      tags:
        - Authors
      summary: Delete an author
      operationId: deleteAuthor
      parameters:
        - in: query
          name: authorId
          description: ID of the author to delete
          required: true
          schema:
            type: string
      responses:
        200:
          description: Author deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200'
  /emprunts:
    post:
      tags:
        - Borrowings
      summary: Borrow a book
      operationId: borrowBook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Emprunt'
      responses:
        200:
          description: Borrowing recorded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200'
  /books/{bookId}/authors/{authorId}:
    put:
      summary: update author's book
      parameters:
        - in: path
          name: bookId
          required: true
          schema:
            type: integer
            format: int64
          description: ID book to update
        - in: path
          name: authorId
          required: true
          schema:
            type: integer
            format: int64
          description: New Id author
      responses:
        '200':
          description: Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200'
        '404':
          description: Book not found
  /books/authors:
    put:
      summary: Update authors for multiple books
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  bookId:
                    type: integer
                    format: int64
                    description: The ID of the book to update
                  authorId:
                    type: integer
                    format: int64
                    description: The ID of the new author
                required:
                  - bookId
                  - authorId
      responses:
        '200':
          description: Update successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200'
  /books/import:
    post:
      tags:
        - Books
      summary: Import books from file
      operationId: importBooks
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                data:
                  $ref: '#/components/schemas/ImportData'
      responses:
        200:
          description: List of imported books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /authors/import:
    post:
      tags:
        - Authors
      summary: Import authors from file
      operationId: importAuthors
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                data:
                  $ref: '#/components/schemas/ImportData'
      responses:
        200:
          description: List of imported authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        author:
          # TODO1: set it as a component with properties : id, name, sex (M or F)
          $ref: '#/components/schemas/Author'
        CrupdateBook:
          $ref: '#/components/schemas/CrupdateBook'
    Author:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        sex:
          type: string
          enum:
            - M
            - F
    Visitor:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        reference:
          type: string
    CrupdateBook:
      type: object
      properties:
        ID:
          type: integer
        bookName:
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
        releaseDate:
          type: string
          format: date
    DefaultResponse:
      type: object
      properties:
        status:
          type: object
          properties:
            code:
              type: integer
            message:
              type: string
        body:
          type: object
    Response200:
      allOf:
        - $ref: '#/components/schemas/DefaultResponse'
        - type: object
          properties:
            body:
              type: object
              properties:
                error:
                  type: string
              example:
                error: "successfuly Request"
    ImportAuthor:
      type: object
      properties:
        authorName:
          type: string
        sex:
          type: string
          enum:
            - M
            - F
      required:
        - authorName
        - sex

    ImportBook:
      type: object
      properties:
        bookName:
          type: string
        author:
          type: string
          description: ID of the author
        pageNumbers:
          type: integer
        topic:
          type: string
        releaseDate:
          type: string
          format: date
        idAuthor:
          type: string
          description: ID of the author
      required:
        - bookName
        - author
        - pageNumbers
        - topic
        - releaseDate
        - idAuthor
    ImportData:
      oneOf:
        - $ref: '#/components/schemas/ImportAuthor'
        - $ref: '#/components/schemas/ImportBook'
  parameters:
    queryPagination:
      in: query
      name: page
      description: Page number
      required: false
      schema:
        type: integer
        default: 1

    pathPagination:
      in: path
      name: page
      required: true
      schema:
        type: integer
        default: 1
